name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [windows-2019]

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    
    - name: Restore NuGet packages
      run: nuget restore BugGuardian.MVC.sln
    
    - name: Build the Solution
      run: msbuild BugGuardian.MVC.sln /p:Configuration=Release

    - name: Publish the Application
      run: |
        msbuild BugGuardian.MVC.sln /p:Configuration=Release /p:OutputPath=$(Build.ArtifactStagingDirectory)/publish

    - name: List Files in Publish Directory
      run: Get-ChildItem -Path $(Build.ArtifactStagingDirectory)/publish -Recurse | Out-File -FilePath publish_contents.txt; type publish_contents.txt

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-core-app
        path: $(Build.ArtifactStagingDirectory)/publish
