name: CI
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: [windows-2019]
    steps:
    - uses: actions/checkout@v2
      #Setup Ms build
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      #Setup Nuget
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      #Restore Nuget Packages
    - name: Restore NuGet packages
      run: nuget restore BugGuardian.MVC.sln
      #Build dotnet Solution
    - name: Build the Solution
      run: msbuild BugGuardian.MVC.sln /p:Configuration=Release
      #Publish dll's
    - name: Publish the Application
      run: |
        msbuild BugGuardian.MVC.sln /p:Configuration=Release /p:OutputPath=./publish
      #publish Artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-core-app
        path: ./publish
