name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: windows-2019

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: dotnet-core-app
        path: ${{ runner.temp }}\filtered

    - name: List Downloaded Artifact
      run: |
        echo "Listing contents of downloaded artifact directory:"
        dir ${{ runner.temp }}\filtered

    - name: Check Artifact Directory
      run: |
        if (Test-Path "${{ runner.temp }}\filtered") {
          Write-Output "Artifact directory exists."
        } else {
          Write-Output "Artifact directory does not exist."
        }

    - name: Deploy to Windows Server
      env:
        SERVER_USER: ${{ secrets.WINDOWS_SERVER_USER }}
        SERVER_PASSWORD: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
        SERVER_HOST: ${{ secrets.WINDOWS_SERVER_HOST }}
      run: |
        echo "Starting deployment to Windows Server"
        $sourcePath = "${{ runner.temp }}\filtered\*"
        $destinationPath = "C:\inetpub\wwwroot\dotnetsample"
        if (-not (Test-Path $destinationPath)) { New-Item -ItemType Directory -Path $destinationPath }
        Copy-Item -Path $sourcePath -Destination $destinationPath -Recurse
        Invoke-Command -ComputerName $env:SERVER_HOST -Credential (New-Object PSCredential($env:SERVER_USER, (ConvertTo-SecureString $env:SERVER_PASSWORD -AsPlainText -Force))) -ScriptBlock { & "C:\path\to\deploy.ps1" }
