name: Dotnet CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [windows-2019]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Ms-Build
        uses: microsoft/setup-msbuild@v2

      - name: Nuget Setup
        uses: NuGet/setup-nuget@v2.0.0

      - name: Nuget restore
        run: nuget restore BugGuardian.MVC.sln

      - name: Build solution
        run: msbuild BugGuardian.MVC.sln /p:Configuration=Release

      - name: Publish application
        run: msbuild BugGuardian.MVC.sln /p:Configuration=Release /p:OutputPath=${{runner.temp}}\publish

      - name: List content from publish path
        run: |
         $publishpath = "${{runner.temp}}\publish"
         Get-ChildItem -Path $publishpath -recursive          
